# Question #8

Please write another unit test so that I can test line 34 in `api.py`:

```
response.raise_for_status() 
```
---

# Answer #8

Sure! Here's an example unit test that you can add to test_api.py to test the raise_for_status() call in api.py:

```python

import responses

class TestApiClient(unittest.TestCase):
    def setUp(self):
        # Set up an ApiClient object
        self.client = ApiClient()

    @responses.activate
    def test_fetch_data_raises_for_status(self):
        # Mock the API response to return a 404 error
        responses.add(
            responses.GET,
            f"{os.environ['ACTITIME_URL']}timetrack",
            status=404,
        )

        # Call the fetch_data method
        with self.assertRaises(requests.exceptions.HTTPError):
            self.client.fetch_data()
```

This test sets up a mock response to return a 404 error, which will cause `raise_for_status()` to raise an exception. The test then uses assertRaises to check that this exception is raised when `fetch_data()` is called.

---

# Action #8

Add the new unit test:

```bash

cat <<EOT >> tests/test_api.py

    @responses.activate
    def test_fetch_data_raises_for_status(self):
        # Mock the API response to return a 404 error
        responses.add(
            responses.GET,
            f"{os.environ['ACTITIME_URL']}timetrack",
            status=404,
        )

        # Call the fetch_data method
        with self.assertRaises(requests.exceptions.HTTPError):
            self.client.fetch_data()
EOT
```

View the coverage report again:

```bash
coverage run -m unittest discover -s tests && \
coverage report && \
coverage html && \
open htmlcov/index.html
```

---

# Next

[Chat 9](9.md)